version: '3.8'
services:
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes: # optional to preserve database after container is deleted.
      - ./database-data-mongo:/data/db